### ISSUE TITLE
Adicionando e removendo um cartão tokenizado

### ISSUE THREAD

**Issue by rwerlich** [filipegar/MaxiPago#3]
Olá.

É normal não ser enviado o CVV para salvar o cartão?

Desde já obrigado pela documentação

**Comment by filipegar** [comment]
Oi, @rwerlich 
Eu particularmente nunca usei o recurso nos meus projetos, mas segundo a documentação [aqui](https://developers.maxipago.com/apidocs/requisicoes-de-cadastro/salvar-um-cartao-na-base/) e [aqui (página 65)](https://www.maxipago.com/docs/maxiPago_API_Ultima.pdf) é assim mesmo. 
E faz sentido - pelo PCI DSS 3 você deve armazenar apenas o token retornado pela API, já que seu ambiente não será homologado. O CVV deve ser solicitado ao cliente em todas as compras. A exceção é se a transação for marcada como recorrente, daí o CVV não é obrigatório.

Como as transações de cadastro no MaxiPago não são enviadas para o banco, pode ser útil você realizar uma transação Zero Dollar (que confirmará os dados enviados) e, baseado nesse retorno, dar o próximo passo para tokenizar ou não. Também dá para tokenizar direto na transação de venda, se você quiser.
