### ISSUE TITLE
Tamanho do token

### ISSUE THREAD

**Issue by theoneit** [filipegar/MaxiPago#4]
Olá!

Recebi um token com mais de 24 chars da maxi pago, e por isso está gerando erro.

**Comment by filipegar** [comment]
@theoneit hahah curioso.
Esse check do strlen foi colocado de propósito, depois de eu bater um papo com o suporte deles.

Anyway, amanhã eu carrego um commit mudando para >=24 e publico uma nova versão. Deve resolver seu problema. ;)

**Comment by theoneit** [comment]
Obrigado Filipe!

To tendo outro problema agora, quando virei pra produção? Sandbox funciona perfeitamente..

Consegue me dar um help?

**Comment by theoneit** [comment]
Filipe,

Acho que não precisa mais. Eles que estavam me enviando o token errado.

Obrigado.
